name: Release
on:
  push:
    tags:
      - "*"

env:
  TEAM_ID: "AEYF632Y3N"
  APPLE_ID: "v@2dubs.com"
  APP_NAME: "Wool.app"
  XCODE_PROJECT: "Wool.xcodeproj"
  XCODE_SCHEME: "Wool"
  XCODE_ARCHIVE: "Wool.xcarchive"
  BUILD_DIR: "build"
  EXPORT_OPTIONS_PLIST: "Wool/ExportOptions.plist"
  DMG_FILE_NAME: "Wool.dmg"
  DMG_BACKGROUND_FILE_NAME: "./Assets/wool_bg@2x.png"

jobs:
  build-and-release:
    runs-on: macos-26
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Get Version from Tag
        id: version
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Select Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode_26.1.app/Contents/Developer
          xcodebuild -version

      - name: Check Swift Version
        run: swift --version

      - name: Set version
        run: |
          agvtool new-version ${{ steps.version.outputs.tag }}
          agvtool new-marketing-version ${{ steps.version.outputs.tag }}

      - name: Install Certificates
        run: |
          # https://docs.github.com/en/actions/deployment/deploying-xcode-applications/installing-an-apple-certificate-on-macos-runners-for-xcode-development
          APPLE_DEVELOPER_CERTIFICATE_PATH=$RUNNER_TEMP/madev.p12
          DEVELOPER_ID_APPLICATION_CERTIFICATE_PATH=$RUNNER_TEMP/devid.p12
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
          echo -n "$APPLE_DEVELOPER_CERTIFICATE" | base64 --decode -o $APPLE_DEVELOPER_CERTIFICATE_PATH
          echo -n "$DEVELOPER_ID_APPLICATION_CERTIFICATE" | base64 --decode -o $DEVELOPER_ID_APPLICATION_CERTIFICATE_PATH
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security import $APPLE_DEVELOPER_CERTIFICATE_PATH -P "$APPLE_DEVELOPER_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security import $DEVELOPER_ID_APPLICATION_CERTIFICATE_PATH -P "$DEVELOPER_ID_APPLICATION_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH
        env:
          DEVELOPER_ID_APPLICATION_CERTIFICATE: ${{ secrets.DEVELOPER_ID_APPLICATION_CERTIFICATE }}
          DEVELOPER_ID_APPLICATION_PASSWORD: ${{ secrets.DEVELOPER_ID_APPLICATION_PASSWORD }}
          APPLE_DEVELOPER_CERTIFICATE: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE }}
          APPLE_DEVELOPER_PASSWORD: ${{ secrets.APPLE_DEVELOPER_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}

      - name: Clean project
        run: xcodebuild clean

      - name: Build App
        run: |
          xcodebuild archive \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -destination 'generic/platform=macOS' \
            -archivePath "$BUILD_DIR/$XCODE_ARCHIVE"

      - name: Export App
        run: |
          xcodebuild -exportArchive \
            -archivePath "$BUILD_DIR/$XCODE_ARCHIVE" \
            -exportOptionsPlist "$EXPORT_OPTIONS_PLIST" \
            -exportPath "$BUILD_DIR"

      - name: Notarize App
        run: |
          ditto -c -k --sequesterRsrc --keepParent "$BUILD_DIR/$APP_NAME" "$BUILD_DIR/$APP_NAME.zip"
          xcrun notarytool submit \
            --team-id "$TEAM_ID" \
            --apple-id "$APPLE_ID" \
            --password "$NOTARY_PASSWORD" \
            --wait \
            "$BUILD_DIR/$APP_NAME.zip"
          xcrun stapler staple "$BUILD_DIR/$APP_NAME"
        env:
          NOTARY_PASSWORD: ${{ secrets.NOTARY_PASSWORD }}

      - name: Install dmgs tool
        run: |
          curl -L -o dmgs.tar.gz https://github.com/velocityzen/dmgs/releases/latest/download/dmgs.tar.gz
          tar -xzf dmgs.tar.gz
          chmod +x dmgs
          sudo mv dmgs /usr/local/bin/

      - name: Create DMG
        run: |
          ls -al
          dmgs create "$BUILD_DIR/$APP_NAME" "$DMG_BACKGROUND_FILE_NAME" --output "$DMG_FILE_NAME" --sign "$TEAM_ID"

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: "$DMG_FILE_NAME"
