name: Test
on:
  pull_request_target:
    branches:
      - main

jobs:
  Tests:
    runs-on: macos-15
    steps:
      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.3.0.app/Contents/Developer

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clean project
        run: xcodebuild clean

      - name: Build Unit Tests
        run: |
          xcodebuild build-for-testing -project Wool.xcodeproj -scheme WoolTests -enableCodeCoverage YES -derivedDataPath build

      - name: Run Unit Tests
        run: |
          xcodebuild test-without-building -project Wool.xcodeproj -scheme WoolTests -enableCodeCoverage YES -derivedDataPath build

      - name: Build UI Tests
        run: |
          xcodebuild build-for-testing -project Wool.xcodeproj -scheme WoolUITests -configuration Debug -derivedDataPath build

      - name: Run UI Tests
        run: |
          xcodebuild test-without-building -project Wool.xcodeproj -scheme WoolUITests -configuration Debug -derivedDataPath build
